a=int(input('a kayefsenni kiriting: '))
b=int(input('b kayefsenni kiriting:'))
c=int(input('c kayefsentni kiriting:'))
print('x1=',(-b+(b**2-4*a*c)**0.5)/(2*a))
print('x1=',(-b-(b**2-4*a*c)**0.5)/(2*a))