v=float(input('1-tezligini kiriting (metr/sekun): '))
u=float(input('2- tezligini kiriting (metr/sekun):'))
s=float(input('Masofani kiriting (metr): '))
t=float(input('Vaqtni kiriting (sekun):'))
print('To\'liq masofa bo\'ldi (metr)',(v+u)*t+s)